# Generated by Django 5.2.2 on 2025-12-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('fonction', models.CharField(blank=True, max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('nb_annees_experience', models.PositiveIntegerField(default=0)),
                ('fenetre', models.CharField(blank=True, max_length=50)),
                ('telephone1', models.CharField(max_length=30)),
                ('telephone2', models.CharField(blank=True, max_length=30)),
                ('ville_residence', models.CharField(blank=True, max_length=120)),
                ('code_ville', models.CharField(blank=True, max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenants', to='formations.classe')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenants', to='formations.formation')),
            ],
            options={
                'ordering': ['nom_complet'],
                'indexes': [models.Index(fields=['classe', 'formation'], name='apprenants__classe__04fe4a_idx')],
                'constraints': [models.UniqueConstraint(fields=('classe', 'nom_complet'), name='unique_nom_par_classe'), models.UniqueConstraint(fields=('formation', 'telephone1'), name='unique_tel1_par_formation')],
            },
        ),
    ]
