# Generated by Django 6.0 on 2026-04-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apprenants", "0007_apprenant_presence_controls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apprenant",
            name="c1",
            field=models.CharField(
                blank=True, choices=[("PR", "Present"), ("AB", "Absent")], default="", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="apprenant",
            name="c2",
            field=models.CharField(
                blank=True, choices=[("PR", "Present"), ("AB", "Absent")], default="", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="apprenant",
            name="c3",
            field=models.CharField(
                blank=True, choices=[("PR", "Present"), ("AB", "Absent")], default="", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="apprenant",
            name="c4",
            field=models.CharField(
                blank=True, choices=[("PR", "Present"), ("AB", "Absent")], default="", max_length=2
            ),
        ),
    ]
