# Generated by Django

from django.db import migrations
import unicodedata

def normalize_name(text):
    if not text:
        return ""
    text = str(text).strip().lower()
    # Remove accents
    normalized = unicodedata.normalize('NFKD', text)
    text = "".join([c for c in normalized if not unicodedata.combining(c)])
    # Remove extra spaces
    text = " ".join(text.split())
    return text


def fit_apprenant_update(Apprenant, field_name, value):
    field = Apprenant._meta.get_field(field_name)
    max_length = getattr(field, "max_length", None)
    if max_length and isinstance(value, str):
        return value[:max_length]
    return value


def fit_apprenant_updates(Apprenant, updates):
    return {
        field_name: fit_apprenant_update(Apprenant, field_name, value)
        for field_name, value in updates.items()
    }


def can_use_telephone1(Apprenant, apprenant, telephone):
    telephone = fit_apprenant_update(Apprenant, "telephone1", telephone)
    if not telephone or not apprenant.formation_id:
        return bool(telephone)
    return not (
        Apprenant.objects.filter(formation_id=apprenant.formation_id, telephone1=telephone)
        .exclude(pk=apprenant.pk)
        .exists()
    )


def fill_apprenant_missing_data(apps, schema_editor):
    """
    Remplissage des données manquantes des apprenants par matching
    avec les tables Appel et ConsolidationRecord.
    """
    Apprenant = apps.get_model('apprenants', 'Apprenant')
    Appel = apps.get_model('appels', 'Appel')
    ConsolidationRecord = apps.get_model('reporting', 'ConsolidationRecord')
    
    updated_count = 0
    skipped_count = 0
    appel_matches = 0
    conso_matches = 0
    
    # Préparer un index des appels par nom normalisé (robuste)
    appel_index = {}
    for appel in Appel.objects.all():
        if appel.nom:
            norm_name = normalize_name(appel.nom)
            # On privilégie l'enregistrement qui a un téléphone
            if norm_name not in appel_index or (appel.telephone1 and not appel_index[norm_name].telephone1):
                appel_index[norm_name] = appel
            
    # Préparer un index des enregistrements de consolidation par nom normalisé (robuste)
    conso_index = {}
    for record in ConsolidationRecord.objects.all():
        if record.nom_complet:
            norm_name = normalize_name(record.nom_complet)
            # On garde le record le plus complet si doublons
            if norm_name not in conso_index or (record.genre and not conso_index[norm_name].genre):
                conso_index[norm_name] = record
    
    for apprenant in Apprenant.objects.all():
        updates = {}
        
        # 1. Données via la liaison avec Classe
        if apprenant.classe:
            # Données professionnelles et de formation
            if not apprenant.intitule_formation_dispensee and apprenant.classe.intitule_formation:
                updates['intitule_formation_dispensee'] = apprenant.classe.intitule_formation
            
            if not apprenant.fenetre and apprenant.classe.fenetre:
                updates['fenetre'] = apprenant.classe.fenetre
            
            if not apprenant.cohorte and apprenant.classe.cohorte:
                updates['cohorte'] = str(apprenant.classe.cohorte)
            
            # Données géographiques via le lieu de la classe
            if apprenant.classe.lieu:
                lieu = apprenant.classe.lieu
                if not apprenant.ville_formation and lieu.ville:
                    updates['ville_formation'] = lieu.ville
                if not apprenant.region and lieu.region:
                    updates['region'] = lieu.region
                if not apprenant.departement and lieu.departement:
                    updates['departement'] = lieu.departement
                if not apprenant.arrondissement and lieu.arrondissement:
                    updates['arrondissement'] = lieu.arrondissement
                if not apprenant.lieu_formation and lieu.nom_lieu:
                    updates['lieu_formation'] = lieu.nom_lieu
                if not apprenant.precision_lieu and lieu.precision:
                    updates['precision_lieu'] = lieu.precision
                if not apprenant.longitude and lieu.longitude:
                    updates['longitude'] = lieu.longitude
                if not apprenant.latitude and lieu.latitude:
                    updates['latitude'] = lieu.latitude
                if not apprenant.code_ville and lieu.ville:
                    updates['code_ville'] = lieu.ville
            
            # Données via la prestation de la classe
            if apprenant.classe.prestation:
                prestation = apprenant.classe.prestation
                if not apprenant.beneficiaire and prestation.beneficiaire:
                    updates['beneficiaire'] = prestation.beneficiaire.nom_structure
                if not apprenant.prestataire and prestation.prestataire:
                    updates['prestataire'] = prestation.prestataire.raison_sociale
                
                # OPTIMISATION: Ville de résidence via le bénéficiaire
                if not apprenant.ville_residence and prestation.beneficiaire and prestation.beneficiaire.ville:
                    updates['ville_residence'] = prestation.beneficiaire.ville
            
            # Données via le formateur de la classe
            if apprenant.classe.formateur:
                formateur = apprenant.classe.formateur
                if not apprenant.tel_formateur and formateur.telephone:
                    updates['tel_formateur'] = formateur.telephone
        
        # 2. Données via la liaison directe avec Formation
        if apprenant.formation:
            if not apprenant.intitule_formation_solicitee and apprenant.formation.nom:
                updates['intitule_formation_solicitee'] = apprenant.formation.nom
            if not apprenant.intitule_formation_dispensee and apprenant.formation.nom:
                updates['intitule_formation_dispensee'] = apprenant.formation.nom
        
        # 3. Matching par nom normalisé
        norm_appr_name = normalize_name(apprenant.nom_complet)
        
        if norm_appr_name:
            # Correspondance avec ConsolidationRecord
            if norm_appr_name in conso_index:
                record = conso_index[norm_appr_name]
                conso_matches += 1
                
                if not apprenant.genre and record.genre:
                    updates['genre'] = record.genre
                if not apprenant.age and record.age:
                    updates['age'] = record.age
                if not apprenant.fonction and record.fonction:
                    updates['fonction'] = record.fonction
                if not apprenant.qualification and record.qualification:
                    updates['qualification'] = record.qualification
                if not apprenant.nb_annees_experience and record.nb_annees_experience is not None:
                    updates['nb_annees_experience'] = record.nb_annees_experience
                if not apprenant.ville_residence and record.ville_residence:
                    updates['ville_residence'] = record.ville_residence
                if not apprenant.departement and record.departement:
                    updates['departement'] = record.departement
                if not apprenant.arrondissement and record.arrondissement:
                    updates['arrondissement'] = record.arrondissement
                
            # Correspondance avec Appel
            if norm_appr_name in appel_index:
                appel = appel_index[norm_appr_name]
                appel_matches += 1
                
                if not apprenant.telephone1 and can_use_telephone1(
                    Apprenant, apprenant, appel.telephone1
                ):
                    updates['telephone1'] = appel.telephone1
                if not apprenant.telephone2 and appel.telephone2:
                    updates['telephone2'] = appel.telephone2
                
                if not apprenant.beneficiaire and appel.beneficiaire:
                    updates['beneficiaire'] = appel.beneficiaire
                if not apprenant.prestataire and appel.prestataire:
                    updates['prestataire'] = appel.prestataire
                if not apprenant.lieu_formation and appel.lieu:
                    updates['lieu_formation'] = appel.lieu
                if not apprenant.ville_formation and appel.lieu:
                    updates['ville_formation'] = appel.lieu
        
        # Appliquer les mises à jour
        if updates:
            Apprenant.objects.filter(pk=apprenant.pk).update(
                **fit_apprenant_updates(Apprenant, updates)
            )
            updated_count += 1
        else:
            skipped_count += 1
    
    print(f"Apprenants mis à jour: {updated_count}")
    print(f"Match Appels: {appel_matches}")
    print(f"Match Consolidation: {conso_matches}")


class Migration(migrations.Migration):
    dependencies = [
        ('apprenants', '0010_apprenant_phase_and_seed'),
        ('reporting', '0003_widen_fields_for_postgres_import'),
    ]

    operations = [
        migrations.RunPython(fill_apprenant_missing_data, reverse_code=migrations.RunPython.noop),
    ]
