# Generated by Django 6.0 on 2026-05-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apprenants", "0011_fill_apprenant_missing_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="apprenant",
            name="c5",
            field=models.CharField(
                blank=True,
                choices=[("PR", "Present"), ("AB", "Absent")],
                default="",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="apprenant",
            name="c6",
            field=models.CharField(
                blank=True,
                choices=[("PR", "Present"), ("AB", "Absent")],
                default="",
                max_length=2,
            ),
        ),
    ]
