# Generated by Django 5.2.16 on 2026-08-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0013_apprenant_code_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='c10',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='c7',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='c8',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='c9',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('AB', 'Absent')], default='', max_length=2),
        ),
    ]
