# Generated by Django 5.2.9 on 2026-01-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0004_sms_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smslog',
            new_name='apprenants__status_9c1d64_idx',
            old_name='apprenants_status_9e3b67_idx',
        ),
        migrations.RenameIndex(
            model_name='smslog',
            new_name='apprenants__sent_at_b0d65c_idx',
            old_name='apprenants_sent_at_2b9f3c_idx',
        ),
    ]
