import re

file_path = r"F:\NAUMUR\NAUMUR - TRAVAUX EN COURS\Utlisateurs\EYOUM ATOCK\CALL APP\App_PADESCE-main\App_PADESCE-main\templates\appels\index.html"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# 1. Add style for the new features
style_add = """
  .badge.reached { background: #dcfce7; color: #166534; border-color: #bbf7d0; }
  .badge.pending { background: #fefce8; color: #854d0e; border-color: #fef08a; }
  .classe-summary { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 12px; }
  .classe-badge { padding: 6px 12px; border-radius: 12px; border: 1px solid var(--border); background: #fff; font-size: 0.85rem; display: flex; align-items: center; gap: 6px; }
  .clickable-row { cursor: pointer; }
  .clickable-row:hover { background-color: rgba(111,60,195,0.03) !important; }
  .flag-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-top: 10px; border-top: 1px solid var(--border); padding-top: 10px; }
  .btn-danger { background: #fee2e2; color: #991b1b; border: 1px solid #fecaca; }
  .btn-danger:hover { background: #fecaca; }
"""
content = content.replace(
    "  .bulk-progress-bar { height:100%; width:0%; background: linear-gradient(90deg, #18b0ac, #f6c453); transition: width .2s ease; }",
    "  .bulk-progress-bar { height:100%; width:0%; background: linear-gradient(90deg, #18b0ac, #f6c453); transition: width .2s ease; }"
    + style_add,
)

# 2. Add classe summary badges after <h1>
classe_summary_html = """
<div class="classe-summary">
  {% for cp in classe_progress %}
    <div class="classe-badge">
      <strong>{{ cp.classe }}</strong>: 
      {% if cp.reached %}
        <span class="badge reached">Objectif Atteint ✅</span>
      {% else %}
        <span class="badge pending">{{ cp.termines }}/{{ cp.target }} ({{ cp.pct }}%)</span>
      {% endif %}
    </div>
  {% endfor %}
</div>
"""
content = re.sub(r'(<h1 class="h4 mb-2">Appels</h1>)', r"\1" + classe_summary_html, content)

# 3. Add Detail/Edit Modal
detail_modal_html = """
<div id="js-detail-modal" class="modal-backdrop" hidden>
  <div class="modal-panel" style="width: 600px; max-height: 90vh; overflow-y: auto;">
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:15px;">
      <h2 style="margin:0;">Détails de l'apprenant & Réponses</h2>
      <button type="button" class="btn btn-ghost btn-sm" id="js-detail-close">×</button>
    </div>
    <div id="js-detail-info" style="display:grid; grid-template-columns:1fr 1fr; gap:10px; font-size:0.9rem; margin-bottom:15px; background:rgba(0,0,0,0.02); padding:10px; border-radius:8px;">
      <!-- Filled by JS -->
    </div>
    
    <form id="js-detail-form">
      <div style="margin: 10px 0; border: 1px solid var(--border); padding: 10px; border-radius: 8px;">
        <h4 style="margin-top:0; margin-bottom: 8px;">Questionnaire de satisfaction</h4>
        <div id="js-detail-questions">
          <!-- Questions 1-9 generated by JS -->
        </div>
        <div class="modal-field">
          <label style="font-size:0.85rem;">Commentaire général</label>
          <textarea name="commentaire" class="input" style="padding:4px; font-size:0.85rem;" rows="2"></textarea>
        </div>
        <div class="modal-field">
          <label style="font-size:0.85rem;">Recommandations</label>
          <textarea name="recommandations" class="input" style="padding:4px; font-size:0.85rem;" rows="2"></textarea>
        </div>
      </div>
      
      <div class="flag-grid">
        <label style="display:flex; align-items:center; gap:6px; font-size:0.85rem;">
          <input type="checkbox" name="flag_pas_forme"> Déjà formé / Pas suivi formation
        </label>
        <label style="display:flex; align-items:center; gap:6px; font-size:0.85rem;">
          <input type="checkbox" name="flag_deja_appele"> Déjà appelé auparavant
        </label>
        <label style="display:flex; align-items:center; gap:6px; font-size:0.85rem;">
          <input type="checkbox" name="flag_numero_double"> Numéro double
        </label>
        <label style="display:flex; align-items:center; gap:6px; font-size:0.85rem;">
          <input type="checkbox" name="flag_faux_nom" id="js-detail-faux-nom"> Ce n'est pas son vrai nom
        </label>
      </div>
      <div id="js-detail-vrai-nom-wrap" class="modal-field" style="display:none; margin-top:5px;">
        <label style="font-size:0.85rem;">Vrai nom :</label>
        <input type="text" name="flag_vrai_nom" class="input" style="padding:4px;">
      </div>

      <div id="js-detail-audit" style="margin-top:15px; font-size:0.75rem; color:var(--muted); border-top:1px solid var(--border); padding-top:5px;">
        <!-- Audit info -->
      </div>

      <div class="modal-actions">
        <button type="button" class="btn btn-ghost btn-sm" id="js-detail-cancel">Annuler</button>
        <button type="submit" class="btn btn-primary btn-sm">Enregistrer les modifications</button>
      </div>
    </form>
  </div>
</div>
"""
content = content.replace(
    '<div id="js-termination-modal"', detail_modal_html + '<div id="js-termination-modal"'
)

# 4. Update row clickability
content = content.replace(
    '<tr data-id="{{ a.id }}"', '<tr class="clickable-row" data-id="{{ a.id }}"'
)

# 5. Update Satisfaction Modal (Phone, Stop record, flags)
sat_modal_update = """
    <div class="modal-detail">
      <span class="modal-label">Nom :</span>
      <span id="js-sat-modal-nom">-</span>
      <span style="margin-left:15px;" class="modal-label">Tél :</span>
      <span id="js-sat-modal-phone">-</span>
    </div>
    
    <div style="margin: 10px 0; border: 1px solid var(--border); padding: 10px; border-radius: 8px;">
"""
content = content.replace(
    '<div class="modal-detail">\n      <span class="modal-label">Nom :</span>\n      <span id="js-sat-modal-nom">-</span>\n    </div>',
    sat_modal_update,
)

# Add flags to sat modal
sat_flags_html = """
    <div class="flag-grid" style="margin-bottom:10px;">
        <label style="display:flex; align-items:center; gap:6px; font-size:0.82rem;">
          <input type="checkbox" id="js-sat-flag-pas-forme"> Déjà formé / Pas suivi formation
        </label>
        <label style="display:flex; align-items:center; gap:6px; font-size:0.82rem;">
          <input type="checkbox" id="js-sat-flag-faux-nom"> Faux nom
        </label>
        <label style="display:flex; align-items:center; gap:6px; font-size:0.82rem;">
          <input type="checkbox" id="js-sat-flag-deja-appele"> Déjà appelé
        </label>
        <label style="display:flex; align-items:center; gap:6px; font-size:0.82rem;">
          <input type="checkbox" id="js-sat-flag-numero-double"> Numéro double
        </label>
    </div>
    <div id="js-sat-vrai-nom-wrap" style="display:none; margin-bottom:10px;">
       <input type="text" id="js-sat-vrai-nom" class="input" style="width:100%; padding:6px;" placeholder="Entrez le vrai nom...">
    </div>
"""
content = content.replace(
    '<div id="js-sat-questions">', sat_flags_html + '<div id="js-sat-questions">'
)

# Add "Stop record" button
content = content.replace(
    '<button type="button" class="btn btn-ghost btn-sm" id="js-sat-hide">Masquer (garder l\'appel en cours)</button>',
    '<button type="button" class="btn btn-ghost btn-sm" id="js-sat-stop-record">Arrêter l\'enregistrement</button>\n      <button type="button" class="btn btn-ghost btn-sm" id="js-sat-hide">Masquer</button>',
)

# 6. Update JS logic
js_add = """
    // ── Detail / Edit Logic ──
    const detailModal = document.getElementById("js-detail-modal");
    const detailForm = document.getElementById("js-detail-form");
    const detailQuestions = document.getElementById("js-detail-questions");
    const detailFauxNom = document.getElementById("js-detail-faux-nom");
    const detailVraiNomWrap = document.getElementById("js-detail-vrai-nom-wrap");
    const questionLabels = ["Clarté des exposés", "Interaction formateur", "Maîtrise contenu", "Salle adéquate", "Matériel disponible", "Organisation temps", "Utilité formation", "Adéquation besoins", "Satisfaction globale"];

    function renderDetailQuestions(answers) {
      detailQuestions.innerHTML = "";
      questionLabels.forEach((label, i) => {
        const val = answers ? answers[`q${i+1}`] : 3;
        let radios = "";
        for(let v=1; v<=5; v++) {
          radios += `<label style="margin-left:8px;"><input type="radio" name="q${i+1}" value="${v}" ${val==v?'checked':''}> ${v}</label>`;
        }
        detailQuestions.innerHTML += `<div style="display:flex; justify-content:space-between; margin-bottom:6px; font-size:0.85rem;"><label>${i+1}. ${label}</label><div>${radios}</div></div>`;
      });
    }

    detailFauxNom?.addEventListener("change", () => {
      detailVraiNomWrap.style.display = detailFauxNom.checked ? "block" : "none";
    });

    document.querySelectorAll(".clickable-row").forEach(row => {
      row.addEventListener("click", async (e) => {
        if (e.target.closest(".actions") || e.target.closest(".checkbox-cell") || e.target.closest("button") || e.target.closest("a")) return;
        const id = row.dataset.id;
        detailModal.hidden = false;
        renderDetailQuestions(null);
        document.getElementById("js-detail-info").innerHTML = "Chargement...";
        document.getElementById("js-detail-audit").innerHTML = "";
        
        try {
          const res = await fetch(`/appels/${id}/answers/`);
          const data = await res.json();
          if (!data.ok) throw new Error();
          
          const a = data.appel;
          document.getElementById("js-detail-info").innerHTML = `
            <div><strong>Nom:</strong> ${a.nom}</div>
            <div><strong>Code:</strong> ${a.code}</div>
            <div><strong>Tél 1:</strong> ${a.telephone1||'-'}</div>
            <div><strong>Tél 2:</strong> ${a.telephone2||'-'}</div>
            <div><strong>Prestataire:</strong> ${a.prestataire}</div>
            <div><strong>Statut:</strong> ${a.status_label}</div>
            <div><strong>Initialement verrouillé par:</strong> ${a.locked_by||'-'}</div>
          `;
          
          renderDetailQuestions(data.answers);
          detailForm.commentaire.value = data.answers?.commentaire || "";
          detailForm.recommandations.value = data.answers?.recommandations || "";
          detailForm.flag_pas_forme.checked = a.flag_pas_forme;
          detailForm.flag_deja_appele.checked = a.flag_deja_appele;
          detailForm.flag_numero_double.checked = a.flag_numero_double;
          detailForm.flag_faux_nom.checked = a.flag_faux_nom;
          detailForm.flag_vrai_nom.value = a.flag_vrai_nom || "";
          detailVraiNomWrap.style.display = a.flag_faux_nom ? "block" : "none";
          
          if (data.answers?.modified_by) {
            document.getElementById("js-detail-audit").innerHTML = `Modifié par <strong>${data.answers.modified_by}</strong> le ${new Date(data.answers.modified_at).toLocaleString()}`;
          }
          detailForm.dataset.rowId = id;

        } catch(err) { alert("Erreur de chargement."); detailModal.hidden = true; }
      });
    });

    detailForm.addEventListener("submit", async (e) => {
      e.preventDefault();
      const id = detailForm.dataset.rowId;
      const fd = new FormData(detailForm);
      // Flags are checkboxes
      ["flag_pas_forme", "flag_deja_appele", "flag_numero_double", "flag_faux_nom"].forEach(f => {
        if (!fd.has(f)) fd.append(f, "0"); else fd.set(f, "1");
      });

      try {
        const res = await fetch(`/appels/${id}/answers/`, {
          method: "POST",
          headers: { "X-CSRFToken": csrfToken },
          body: fd
        });
        const data = await res.json();
        if (data.ok) {
          alert("Enregistré avec succès.");
          detailModal.hidden = true;
          // Optionnel: rafraîchir la ligne ou la page
        } else alert(data.error || "Erreur.");
      } catch(err) { alert("Erreur réseau."); }
    });

    document.getElementById("js-detail-close").onclick = () => detailModal.hidden = true;
    document.getElementById("js-detail-cancel").onclick = () => detailModal.hidden = true;

    // ── Satisfaction Modal Enrichment ──
    const satFauxNom = document.getElementById("js-sat-flag-faux-nom");
    const satVraiNomWrap = document.getElementById("js-sat-vrai-nom-wrap");
    satFauxNom.addEventListener("change", () => {
      satVraiNomWrap.style.display = satFauxNom.checked ? "block" : "none";
    });

    const stopRecBtn = document.getElementById("js-sat-stop-record");
    stopRecBtn.addEventListener("click", () => {
       const id = satModal.dataset.rowId;
       const row = document.querySelector(`tr[data-id="${id}"]`);
       const state = getRecordState(row);
       if (state?.recorder && state.recorder.state !== "inactive") {
         state.recorder.stop();
         state.stream?.getTracks().forEach(t => t.stop());
         alert("Enregistrement arrêté. Vous pouvez finir de remplir le formulaire.");
       }
    });
"""

# Inject JS before end of script
content = content.replace("})();", js_add + "\n  })();")

# Update satisfyterminer to include flags
sat_terminer_js = """
        const shouldRappeler = satModalRappel?.checked;
        const rappelAt = satModalRappelAt?.value;
        const de_forme_check = document.getElementById("js-sat-modal-deja-forme")?.checked;
        
        currentSatFormData = new FormData();
        for (let i = 1; i <= 9; i++) {
            const checked = document.querySelector(`input[name="q${i}"]:checked`);
            if (checked) currentSatFormData.append(`q${i}`, checked.value);
        }
        currentSatFormData.append("commentaire", document.getElementById("js-sat-commentaire").value);
        currentSatFormData.append("recommandations", document.getElementById("js-sat-recommandations").value);
        
        // Add signals
        currentSatFormData.append("flag_pas_forme", document.getElementById("js-sat-flag-pas-forme").checked ? "1" : "0");
        currentSatFormData.append("flag_faux_nom", document.getElementById("js-sat-flag-faux-nom").checked ? "1" : "0");
        currentSatFormData.append("flag_vrai_nom", document.getElementById("js-sat-vrai-nom").value);
        currentSatFormData.append("flag_deja_appele", document.getElementById("js-sat-flag-deja-appele").checked ? "1" : "0");
        currentSatFormData.append("flag_numero_double", document.getElementById("js-sat-flag-numero-double").checked ? "1" : "0");
        currentSatFormData.append("deja_forme", de_forme_check ? "1" : "0");

        satModal.hidden = true;
"""
content = re.sub(
    r"const\s+shouldRappeler\s+=\s+satModalRappel\?\.checked;.*?satModal\.hidden\s+=\s+true;",
    sat_terminer_js,
    content,
    flags=re.DOTALL,
)

# Update startRecording to pre-fill from detail endpoint if status is a_rappeler
start_rec_update = """
    async function startRecording(row) {
      const id = row.dataset.id;
      const status = row.dataset.status;
      
      const satModal = document.getElementById("js-satisfaction-modal");
      if (satModal) {
          // Default values
          document.querySelectorAll("#js-sat-questions input[type=radio][value='3']").forEach(r => r.checked = true);
          document.getElementById("js-sat-commentaire").value = "";
          document.getElementById("js-sat-recommandations").value = "";
          
          if (status === 'a_rappeler') {
             try {
               const res = await fetch(`/appels/${id}/answers/`);
               const data = await res.json();
               if (data.ok && data.answers) {
                  for(let i=1; i<=9; i++) {
                     const v = data.answers[`q${i}`];
                     if(v) {
                        const rad = document.querySelector(`#js-sat-questions input[name="q${i}"][value="${v}"]`);
                        if(rad) rad.checked = true;
                     }
                  }
                  document.getElementById("js-sat-commentaire").value = data.answers.commentaire || "";
                  document.getElementById("js-sat-recommandations").value = data.answers.recommandations || "";
               }
             } catch(e){}
          }
          
          const smr = document.getElementById("js-sat-modal-rappel");
          if (smr) smr.checked = false;
          // ... rest of startRecording ...
"""
# This is complex to regex replace, I'll do a simpler replacement for the pre-fill logic
content = content.replace(
    "document.querySelectorAll(\"#js-sat-questions input[type=radio][value='3']\").forEach(r => r.checked = true);",
    '// Default values\n          document.querySelectorAll("#js-sat-questions input[type=radio][value=\'3\']").forEach(r => r.checked = true);\n          if (row.dataset.status === "a_rappeler") {\n             try {\n               const res = await fetch(`/appels/${id}/answers/`);\n               const data = await res.json();\n               if (data.ok && data.answers) {\n                 for(let i=1; i<=9; i++) {\n                   const v = data.answers[`q${i}`];\n                   if(v) { const r = document.querySelector(`#js-sat-questions input[name="q${i}"][value="${v}"]`); if(r) r.checked = true; }\n                 }\n                 document.getElementById("js-sat-commentaire").value = data.answers.commentaire || "";\n                 document.getElementById("js-sat-recommandations").value = data.answers.recommandations || "";\n               }\n             } catch(e){}\n          }',
)

# Add Phone visibility
content = content.replace(
    "satModal.dataset.rowId = id;",
    'satModal.dataset.rowId = id;\n          document.getElementById("js-sat-modal-phone").textContent = row.dataset.phone || "-";',
)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Patch complete.")
