# Generated by Django 6.0 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BeneficiaireUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("beneficiaire_nom", models.CharField(max_length=255)),
                ("prestataire_nom", models.CharField(max_length=255)),
                ("fichier", models.FileField(upload_to="beneficiaires/uploads/")),
                ("est_rejete", models.BooleanField(default=False)),
                ("erreurs", models.TextField(blank=True)),
                ("erreurs_types", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
