# Generated by Django 6.0 on 2026-01-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaires", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiaireupload",
            name="recap_stats",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
