# Generated by Django 5.2.2 on 2025-12-14 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnqueteEnvironnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('heure_enregistrement', models.TimeField(blank=True, null=True)),
                ('tables', models.BooleanField(default=False)),
                ('chaises', models.BooleanField(default=False)),
                ('ecran', models.BooleanField(default=False)),
                ('videoprojecteur', models.BooleanField(default=False)),
                ('ventilation', models.BooleanField(default=False)),
                ('eclairage', models.BooleanField(default=False)),
                ('aeration', models.BooleanField(default=False)),
                ('prises_electriques', models.BooleanField(default=False)),
                ('salle_propre', models.BooleanField(default=False)),
                ('salle_accessible', models.BooleanField(default=False)),
                ('salle_securisee', models.BooleanField(default=False)),
                ('signaletique', models.BooleanField(default=False)),
                ('commodite', models.BooleanField(default=False)),
                ('accessibilite', models.BooleanField(default=False)),
                ('securite', models.BooleanField(default=False)),
                ('acces_eau', models.BooleanField(default=False)),
                ('commentaire_salle', models.TextField(blank=True)),
                ('commentaire_global', models.TextField(blank=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_environnement', to='formations.classe')),
                ('enqueteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environnement_saisies', to=settings.AUTH_USER_MODEL)),
                ('inspecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.inspecteur')),
            ],
            options={
                'ordering': ['-date', 'classe'],
                'indexes': [models.Index(fields=['classe'], name='environneme_classe__572986_idx')],
            },
        ),
    ]
