# Generated by Django 6.0 on 2026-02-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0005_appel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelImportArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_mode', models.CharField(blank=True, max_length=50)),
                ('source_code', models.CharField(blank=True, max_length=50)),
                ('snapshot', models.JSONField(default=dict)),
                ('appel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_archives', to='appels.appel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
