# Generated by Django 6.0 on 2026-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0011_call_transcription_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appelanswers',
            name='q3_rythme_formation',
        ),
        migrations.RemoveField(
            model_name='appelanswers',
            name='q4_qualite_supports',
        ),
        migrations.RemoveField(
            model_name='appelanswers',
            name='q5_applicabilite_contenu',
        ),
        migrations.RemoveField(
            model_name='appelanswers',
            name='q6_organisation_logistique',
        ),
        migrations.RemoveField(
            model_name='appelanswers',
            name='q7_respect_programme',
        ),
        migrations.AddField(
            model_name='appelanswers',
            name='q3_maitrise_contenu',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='appelanswers',
            name='q4_salle_adequate',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='appelanswers',
            name='q5_materiel_disponible',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='appelanswers',
            name='q6_organisation_temps',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='appelanswers',
            name='q7_utilite_formation',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True),
        ),
    ]
