# Generated by Django 6.0 on 2026-03-18 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0012_remove_appelanswers_q3_rythme_formation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appel',
            name='flag_deja_appele',
            field=models.BooleanField(default=False, verbose_name='Déjà appelé'),
        ),
        migrations.AddField(
            model_name='appel',
            name='flag_faux_nom',
            field=models.BooleanField(default=False, verbose_name='Faux nom'),
        ),
        migrations.AddField(
            model_name='appel',
            name='flag_numero_double',
            field=models.BooleanField(default=False, verbose_name='Numéro double'),
        ),
        migrations.AddField(
            model_name='appel',
            name='flag_pas_forme',
            field=models.BooleanField(default=False, verbose_name="N'a pas suivi la formation"),
        ),
        migrations.AddField(
            model_name='appel',
            name='flag_vrai_nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vrai nom'),
        ),
        migrations.AddField(
            model_name='appelanswers',
            name='commentaire',
            field=models.TextField(blank=True, default='RAS'),
        ),
        migrations.AddField(
            model_name='appelanswers',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appelanswers',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appel_answers_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appelanswers',
            name='recommandations',
            field=models.TextField(blank=True, default='RAS'),
        ),
    ]
