# Generated by Django 6.0 on 2026-03-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0013_appel_flag_deja_appele_appel_flag_faux_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appelformateurtranscription',
            name='appel_formateur',
        ),
        migrations.RemoveField(
            model_name='appeltranscription',
            name='appel',
        ),
        migrations.DeleteModel(
            name='AppelCGATranscription',
        ),
        migrations.DeleteModel(
            name='AppelFormateurTranscription',
        ),
        migrations.DeleteModel(
            name='AppelTranscription',
        ),
    ]
