# Generated by Django 6.0 on 2026-03-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appels", "0014_remove_appelformateurtranscription_appel_formateur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appelformateur",
            name="commentaires",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appelformateur",
            name="q1_prerequis_apprenants",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appelformateur",
            name="q2_interaction_apprenants",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appelformateur",
            name="q3_competences_acquises",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appelformateur",
            name="q4_gestion_administrative",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appelformateur",
            name="q5_gestion_financiere",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appelformateur",
            name="q6_communication",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appelformateur",
            name="recommandations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appelformateur",
            name="satisfaction_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
