# Generated by Django 6.0 on 2026-05-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0012_apprenant_c5_apprenant_c6'),
        ('formations', '0008_remove_test_formateurs_zap_yanava'),
        ('presences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(max_length=255, verbose_name='Thème de la séance')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('conformite', models.CharField(blank=True, choices=[('conforme', 'Conforme'), ('non_conforme', 'Non Conforme')], max_length=20, verbose_name='Conformité')),
                ('type_controle', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6')], max_length=2)),
                ('duree_prevue_formation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Durée prévue de la formation')),
                ('formateur1_nom', models.CharField(blank=True, max_length=255, verbose_name='Nom du formateur 1')),
                ('formateur1_telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone formateur 1')),
                ('formateur2_nom', models.CharField(blank=True, max_length=255, verbose_name='Nom du formateur 2')),
                ('formateur2_telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone formateur 2')),
                ('formateur3_nom', models.CharField(blank=True, max_length=255, verbose_name='Nom du formateur 3')),
                ('formateur3_telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone formateur 3')),
                ('teams_sent_at', models.DateTimeField(blank=True, null=True)),
                ('teams_file_url', models.URLField(blank=True, max_length=1000)),
                ('teams_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', 'classe__code', 'type_controle'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='presence',
            name='presence_unique_par_jour',
        ),
        migrations.AddField(
            model_name='presence',
            name='heure_presence',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='moyen_enregistrement',
            field=models.CharField(blank=True, choices=[('', 'Non renseigné'), ('C', 'Code'), ('P', 'Papier'), ('R', 'Rien')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='presence',
            name='presence',
            field=models.CharField(choices=[('PR', 'Présent'), ('AB', 'Absent')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent')], default='absent', max_length=10),
        ),
        migrations.AddField(
            model_name='presencecontrol',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_controls', to='formations.classe'),
        ),
        migrations.AddField(
            model_name='presencecontrol',
            name='enqueteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_controls_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presencecontrol',
            name='inspecteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_controls', to='formations.inspecteur'),
        ),
        migrations.AddField(
            model_name='presence',
            name='controle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='presences.presencecontrol'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['controle'], name='presences_p_control_f7b5a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(fields=('controle', 'apprenant'), name='presence_unique_par_controle'),
        ),
        migrations.AddIndex(
            model_name='presencecontrol',
            index=models.Index(fields=['classe', 'type_controle'], name='presences_p_classe__d21b9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='presencecontrol',
            constraint=models.UniqueConstraint(fields=('classe', 'type_controle'), name='presence_control_unique_type_par_classe'),
        ),
    ]
