# Generated by Django 5.2.9 on 2026-01-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consolidationrecord',
            new_name='reporting_c_code_c4eaac_idx',
            old_name='reporting_c_code_96f31f_idx',
        ),
        migrations.RenameIndex(
            model_name='consolidationrecord',
            new_name='reporting_c_nom_com_bc5d3c_idx',
            old_name='reporting_c_nom_co_4906c5_idx',
        ),
    ]
