"""
Django settings for App_PADESCE project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import os
import tempfile
from pathlib import Path
from urllib.parse import unquote, urlparse


ENV_FILE_OVERRIDE_KEYS = {
    "ANTHROPIC_API_KEY",
    "BACKUP_RETENTION_DAYS",
    "BACKUP_TRIGGER_TOKEN",
    "CGA_PUBLIC_API_KEY",
    "DEFAULT_FROM_EMAIL",
    "DEPLOYMENT_REPORT_EMAIL_TO",
    "DJANGO_ALLOWED_HOSTS",
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "DJANGO_DEBUG",
    "EMAIL_BACKEND",
    "EMAIL_HOST",
    "EMAIL_HOST_PASSWORD",
    "EMAIL_HOST_USER",
    "EMAIL_PORT",
    "EMAIL_TIMEOUT",
    "EMAIL_USE_SSL",
    "EMAIL_USE_TLS",
    "EXPORT_API_KEY",
    "HF_TOKEN",
    "HUGGINGFACE_BACKUP_COMMIT_PREFIX",
    "HUGGINGFACE_BACKUP_SOURCE_URL",
    "HUGGINGFACE_BACKUP_SYNC_ENABLED",
    "HUGGINGFACE_BACKUP_SYNC_REQUIRED",
    "HUGGINGFACE_SPACE_DB_PATH",
    "HUGGINGFACE_SPACE_META_PATH",
    "HUGGINGFACE_SPACE_REPO_ID",
    "HUGGINGFACE_SPACE_REPO_TYPE",
    "HUGGINGFACE_SPACE_REVISION",
    "HUGGINGFACE_SPACE_URL",
    "HUGGINGFACE_TOKEN",
    "MICROSOFT_GRAPH_CLIENT_ID",
    "MICROSOFT_GRAPH_CLIENT_SECRET",
    "MICROSOFT_GRAPH_PRIMARY_DOMAIN",
    "MICROSOFT_GRAPH_REDIRECT_URI",
    "MICROSOFT_GRAPH_TENANT_ID",
    "MICROSOFT_TEAMS_DEFAULT_TEAM_ID",
    "OPENAI_API_KEY",
    "PADESCE_CHAT_API_TIMEOUT",
    "PADESCE_CHAT_API_TOKEN",
    "PADESCE_CHAT_API_URL",
    "PADESCE_RAG_API_TIMEOUT",
    "PADESCE_RAG_API_TOKEN",
    "PADESCE_RAG_API_URL",
    "REPORT_EMAIL_TO",
    "REPORT_TRIGGER_TOKEN",
}


def load_env_file(env_path: Path, *, override_keys: set[str] | None = None) -> None:
    """
    Charge un fichier .env simple (clé=valeur, sans quotes) si présent.
    Ne remplace pas une variable déjà définie, sauf pour les clés explicitement
    gérées par le fichier synchronisé.
    """
    override_keys = override_keys or set()
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if (
            not line
            or line.startswith("#")
            or line.startswith("<<<<<<<")
            or line.startswith("=======")
            or line.startswith(">>>>>>>")
            or "=" not in line
        ):
            continue
        key, value = line.split("=", 1)
        key = key.strip().lstrip("\ufeff")
        value = value.strip()
        if not key or any(char.isspace() for char in key):
            continue
        if key in override_keys:
            os.environ[key] = value
        else:
            os.environ.setdefault(key, value)


def _int_env(name: str, default: int, *, minimum: int = 0) -> int:
    raw_value = str(os.getenv(name, str(default)) or str(default)).strip()
    try:
        value = int(raw_value)
    except (TypeError, ValueError):
        return default
    return max(value, minimum)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement locales si presentes.
load_env_file(BASE_DIR / ".env")
load_env_file(BASE_DIR / ".env.local", override_keys=ENV_FILE_OVERRIDE_KEYS)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")
PUBLIC_CONSULTANT_ACCESS = os.getenv("PUBLIC_CONSULTANT_ACCESS", "False").lower() in (
    "1",
    "true",
    "yes",
)
# This exceptional bypass must only be enabled explicitly for a controlled
# environment. It must never grant a session merely because an environment
# variable was omitted.
PUBLIC_ANALYSIS_AUTO_LOGIN = os.getenv("PUBLIC_ANALYSIS_AUTO_LOGIN", "False").lower() in (
    "1",
    "true",
    "yes",
)
PUBLIC_ANALYSIS_AUTO_LOGIN_USERNAME = os.getenv(
    "PUBLIC_ANALYSIS_AUTO_LOGIN_USERNAME",
    "",
).strip()
PUBLIC_ANALYSIS_AUTO_LOGIN_PASSWORD = os.getenv(
    "PUBLIC_ANALYSIS_AUTO_LOGIN_PASSWORD",
    "",
)
PUBLIC_ANALYSIS_AUTO_LOGIN_PREFIXES = (
    "/satisfaction-apprenants/analyse/",
    "/satisfaction-formateurs/analyse/",
    "/analyses/fast-stats/",
    "/classe/",
    "/prestation/",
    "/analyse/appels/apprenant/",
    "/analyse/appels/formateur/",
    "/apprenants/",
)
PADESCE_OPERATOR_AUTH_ENABLED = os.getenv("PADESCE_OPERATOR_AUTH_ENABLED", "False").lower() in (
    "1",
    "true",
    "yes",
)
PADESCE_OPERATOR_LOGIN_REQUIRED_GROUPS = tuple(
    group.strip()
    for group in os.getenv("PADESCE_OPERATOR_LOGIN_REQUIRED_GROUPS", "").split(",")
    if group.strip()
)

ALLOWED_HOSTS_ENV = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(",") if host.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*", "app-padesce.onrender.com", "call.naumur.com", "192.168.1.162"]
CSRF_TRUSTED_ORIGINS_ENV = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(",") if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Applications métiers
    "App_PADESCE.core",
    "App_PADESCE.formations",
    "App_PADESCE.apprenants",
    "App_PADESCE.presences",
    "App_PADESCE.satisfaction_apprenants",
    "App_PADESCE.satisfaction_formateurs",
    "App_PADESCE.environnement",
    "App_PADESCE.messaging",
    "App_PADESCE.reporting",
    "App_PADESCE.beneficiaires",
    "App_PADESCE.appels",
]

HAS_CHANNELS = importlib.util.find_spec("channels") is not None
HAS_WHITENOISE = importlib.util.find_spec("whitenoise") is not None
HAS_DJANGO_REDIS = importlib.util.find_spec("django_redis") is not None
HAS_CHANNELS_REDIS = importlib.util.find_spec("channels_redis") is not None
if HAS_CHANNELS:
    INSTALLED_APPS.insert(6, "channels")

MIDDLEWARE = [
    "App_PADESCE.core.middleware.PathPrefixMiddleware",
    "App_PADESCE.core.middleware.FriendlyErrorPagesMiddleware",
    "django.middleware.security.SecurityMiddleware",
]
if HAS_WHITENOISE:
    MIDDLEWARE.append("whitenoise.middleware.WhiteNoiseMiddleware")
MIDDLEWARE += [
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "App_PADESCE.core.middleware.LoginRequiredMiddleware",
    "App_PADESCE.core.middleware.UserActivityMiddleware",
    "App_PADESCE.core.middleware.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "App_PADESCE.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "App_PADESCE.core.context_processors.navbar",
            ],
        },
    },
]

WSGI_APPLICATION = "App_PADESCE.wsgi.application"
if HAS_CHANNELS:
    ASGI_APPLICATION = "App_PADESCE.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def _database_settings_from_env() -> dict:
    database_url = str(os.getenv("DATABASE_URL", "") or "").strip()
    if database_url:
        parsed = urlparse(database_url)
        if parsed.scheme in {"postgres", "postgresql"}:
            return {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": unquote(parsed.path.lstrip("/"))
                or str(os.getenv("POSTGRES_DB", "") or "postgres"),
                "USER": unquote(parsed.username or os.getenv("POSTGRES_USER", "") or ""),
                "PASSWORD": unquote(parsed.password or os.getenv("POSTGRES_PASSWORD", "") or ""),
                "HOST": parsed.hostname or os.getenv("POSTGRES_HOST", "") or "localhost",
                "PORT": str(parsed.port or os.getenv("POSTGRES_PORT", "") or "5432"),
            }

    engine = str(os.getenv("DB_ENGINE", "") or "").strip().lower()
    if engine in {"postgres", "postgresql", "pgsql"}:
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": str(os.getenv("POSTGRES_DB", "") or "postgres"),
            "USER": str(os.getenv("POSTGRES_USER", "") or ""),
            "PASSWORD": str(os.getenv("POSTGRES_PASSWORD", "") or ""),
            "HOST": str(os.getenv("POSTGRES_HOST", "") or "localhost"),
            "PORT": str(os.getenv("POSTGRES_PORT", "") or "5432"),
        }

    sqlite_path = str(os.getenv("SQLITE_PATH", "") or os.getenv("SQLITE_NAME", "") or "").strip()
    sqlite_name = Path(sqlite_path) if sqlite_path else BASE_DIR / "db.sqlite3"
    if not sqlite_name.is_absolute():
        sqlite_name = BASE_DIR / sqlite_name

    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": sqlite_name,
        "OPTIONS": {
            "timeout": int(str(os.getenv("SQLITE_TIMEOUT", "30") or "30")),
        },
    }


DATABASES = {"default": _database_settings_from_env()}

# Token secret pour le déclenchement automatique des backups (GitHub Actions)
BACKUP_TRIGGER_TOKEN = os.getenv("BACKUP_TRIGGER_TOKEN", "")
REPORT_TRIGGER_TOKEN = os.getenv("REPORT_TRIGGER_TOKEN", BACKUP_TRIGGER_TOKEN)
BACKUP_RETENTION_DAYS = os.getenv("BACKUP_RETENTION_DAYS", "30")

# Publication du snapshot SQLite vers le Space Hugging Face du chatbot.
HUGGINGFACE_TOKEN = os.getenv("HUGGINGFACE_TOKEN", os.getenv("HF_TOKEN", ""))
HF_TOKEN = os.getenv("HF_TOKEN", HUGGINGFACE_TOKEN)
HUGGINGFACE_SPACE_REPO_ID = os.getenv("HUGGINGFACE_SPACE_REPO_ID", "JackBrayan17/padesce-bot")
HUGGINGFACE_SPACE_REPO_TYPE = os.getenv("HUGGINGFACE_SPACE_REPO_TYPE", "space")
HUGGINGFACE_SPACE_REVISION = os.getenv("HUGGINGFACE_SPACE_REVISION", "main")
HUGGINGFACE_SPACE_DB_PATH = os.getenv("HUGGINGFACE_SPACE_DB_PATH", "db.sqlite3")
HUGGINGFACE_SPACE_META_PATH = os.getenv("HUGGINGFACE_SPACE_META_PATH", "db_metadata.json")
HUGGINGFACE_SPACE_URL = os.getenv(
    "HUGGINGFACE_SPACE_URL",
    "https://jackbrayan17-padesce-bot.hf.space",
)
HUGGINGFACE_BACKUP_SOURCE_URL = os.getenv(
    "HUGGINGFACE_BACKUP_SOURCE_URL",
    "https://call.naumur.com",
)
HUGGINGFACE_BACKUP_SYNC_ENABLED = os.getenv("HUGGINGFACE_BACKUP_SYNC_ENABLED", "False").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
HUGGINGFACE_BACKUP_SYNC_REQUIRED = os.getenv(
    "HUGGINGFACE_BACKUP_SYNC_REQUIRED", "False"
).lower() in ("1", "true", "yes", "on")
HUGGINGFACE_BACKUP_COMMIT_PREFIX = os.getenv(
    "HUGGINGFACE_BACKUP_COMMIT_PREFIX",
    "Update PADESCE SQLite backup",
)

# Microsoft Graph / Teams
MICROSOFT_GRAPH_TENANT_ID = str(os.getenv("MICROSOFT_GRAPH_TENANT_ID", "") or "").strip()
MICROSOFT_GRAPH_CLIENT_ID = str(os.getenv("MICROSOFT_GRAPH_CLIENT_ID", "") or "").strip()
MICROSOFT_GRAPH_CLIENT_SECRET = str(os.getenv("MICROSOFT_GRAPH_CLIENT_SECRET", "") or "").strip()
MICROSOFT_GRAPH_PRIMARY_DOMAIN = str(os.getenv("MICROSOFT_GRAPH_PRIMARY_DOMAIN", "") or "").strip()
MICROSOFT_GRAPH_REDIRECT_URI = str(os.getenv("MICROSOFT_GRAPH_REDIRECT_URI", "") or "").strip()
MICROSOFT_TEAMS_DEFAULT_TEAM_ID = str(
    os.getenv("MICROSOFT_TEAMS_DEFAULT_TEAM_ID", "") or ""
).strip()
PADESCE_DESCENTE_WORKBOOK_PATH = str(os.getenv("PADESCE_DESCENTE_WORKBOOK_PATH", "") or "").strip()
MICROSOFT_GRAPH_AUTHORITY = (
    f"https://login.microsoftonline.com/{MICROSOFT_GRAPH_TENANT_ID}"
    if MICROSOFT_GRAPH_TENANT_ID
    else ""
)
MICROSOFT_GRAPH_CHANNEL_SCOPES = [
    "openid",
    "profile",
    "offline_access",
    "User.Read",
    "ChannelMessage.Send",
    "Team.ReadBasic.All",
    "Channel.ReadBasic.All",
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Use an absolute URL path so templates and `{% static %}` produce
# predictable URLs (e.g. `/static/...`). Previously missing leading
# slash caused relative URLs and missing assets in some pages.
STATIC_URL = "/static/"
STATIC_DIR = BASE_DIR / "static"
STATICFILES_DIRS = [STATIC_DIR] if STATIC_DIR.exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"
if HAS_WHITENOISE:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "App_PADESCE.core.staticfiles.SafeCompressedManifestStaticFilesStorage",
        },
    }

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "public_space"
CSRF_FAILURE_VIEW = "App_PADESCE.core.error_views.csrf_failure"


def _redis_url_from_env(*names: str) -> str:
    for name in names:
        value = str(os.getenv(name, "") or "").strip()
        if value:
            return value
    return ""


def _cache_backend_key_from_env() -> str:
    explicit_backend = str(os.getenv("PADESCE_CACHE_BACKEND", "") or "").strip().lower()
    if explicit_backend:
        return explicit_backend
    if _redis_url_from_env("PADESCE_REDIS_URL", "REDIS_URL"):
        return "redis"
    return "locmem"


def _cache_settings_from_env() -> dict:
    backend_key = _cache_backend_key_from_env()
    timeout = int(str(os.getenv("PADESCE_CACHE_TIMEOUT", "28800") or "28800"))
    max_entries = int(str(os.getenv("PADESCE_CACHE_MAX_ENTRIES", "5000") or "5000"))
    key_prefix = str(os.getenv("PADESCE_CACHE_KEY_PREFIX", "padesce") or "padesce").strip()

    if backend_key in {"redis", "rediscache", "django-redis", "django_redis"}:
        if not HAS_DJANGO_REDIS:
            raise RuntimeError("Le backend de cache Redis requiert la dependance django-redis.")
        redis_url = _redis_url_from_env("PADESCE_REDIS_URL", "REDIS_URL")
        if not redis_url:
            raise RuntimeError(
                "Aucune URL Redis configuree. Definissez PADESCE_REDIS_URL ou REDIS_URL."
            )
        return {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": redis_url,
                "TIMEOUT": timeout,
                "KEY_PREFIX": key_prefix,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                },
            }
        }

    if backend_key in {"file", "filebased", "file_based"}:
        requested_location = str(os.getenv("PADESCE_CACHE_LOCATION", "") or "").strip()
        location_candidates = [
            Path(requested_location) if requested_location else None,
            BASE_DIR / "data" / "django_cache",
            Path(tempfile.gettempdir()) / "padesce-cache",
            BASE_DIR / ".django_cache",
        ]
        location_path = None
        seen_locations: set[str] = set()
        for candidate in location_candidates:
            if candidate is None:
                continue
            candidate_key = str(candidate)
            if candidate_key in seen_locations:
                continue
            seen_locations.add(candidate_key)
            try:
                candidate.mkdir(parents=True, exist_ok=True)
            except OSError:
                continue
            location_path = candidate
            break
        if location_path is None:
            raise RuntimeError("Impossible d'initialiser un dossier de cache Django ecrivable.")
        return {
            "default": {
                "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
                "LOCATION": str(location_path),
                "TIMEOUT": timeout,
                "OPTIONS": {
                    "MAX_ENTRIES": max_entries,
                },
            }
        }

    if backend_key in {"dummy", "none"}:
        return {
            "default": {
                "BACKEND": "django.core.cache.backends.dummy.DummyCache",
            }
        }

    return {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "padesce-session-cache",
            "TIMEOUT": timeout,
            "OPTIONS": {
                "MAX_ENTRIES": max_entries,
            },
        }
    }


CACHES = _cache_settings_from_env()


def _channel_layer_backend_key_from_env() -> str:
    explicit_backend = str(os.getenv("PADESCE_CHANNEL_LAYER_BACKEND", "") or "").strip().lower()
    if explicit_backend:
        return explicit_backend
    if _redis_url_from_env("PADESCE_CHANNELS_REDIS_URL", "PADESCE_REDIS_URL", "REDIS_URL"):
        return "redis"
    return "memory"


def _channel_layers_from_env() -> dict:
    backend_key = _channel_layer_backend_key_from_env()
    if backend_key in {"memory", "inmemory", "in-memory", "local"}:
        return {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer",
            }
        }
    if backend_key in {"none", "disabled"}:
        return {}
    if backend_key == "redis":
        if not HAS_CHANNELS_REDIS:
            raise RuntimeError("Le channel layer Redis requiert la dependance channels-redis.")
        redis_url = _redis_url_from_env(
            "PADESCE_CHANNELS_REDIS_URL",
            "PADESCE_REDIS_URL",
            "REDIS_URL",
        )
        if not redis_url:
            raise RuntimeError(
                "Aucune URL Redis configuree pour Channels. "
                "Definissez PADESCE_CHANNELS_REDIS_URL, PADESCE_REDIS_URL ou REDIS_URL."
            )
        return {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [redis_url],
                },
            }
        }
    raise RuntimeError(f"Backend de channel layer inconnu: {backend_key}")


if HAS_CHANNELS:
    CHANNEL_LAYERS = _channel_layers_from_env()


# ---------------------------------------------------------------------------
# Sessions :
# - SQLite local : signed_cookies pour éviter un 500 au login si la base est verrouillée
# - PostgreSQL + Redis : cached_db pour accélérer les lectures avec un cache partagé
# - PostgreSQL sans Redis : db pour éviter un cache mémoire différent par worker
# ---------------------------------------------------------------------------
def _session_engine_from_env() -> str:
    explicit_engine = str(os.getenv("PADESCE_SESSION_ENGINE", "") or "").strip()
    if explicit_engine:
        return explicit_engine
    default_db = DATABASES.get("default", {})
    if default_db.get("ENGINE") == "django.db.backends.sqlite3":
        return "django.contrib.sessions.backends.signed_cookies"
    if _cache_backend_key_from_env() == "redis":
        return "django.contrib.sessions.backends.cached_db"
    return "django.contrib.sessions.backends.db"


SESSION_ENGINE = _session_engine_from_env()
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 28800  # 8 heures (en secondes)
SESSION_SAVE_EVERY_REQUEST = False  # ne sauvegarder que si modifiée
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # session survit à la fermeture du navigateur
SESSION_COOKIE_HTTPONLY = True  # non accessible via JavaScript
SESSION_COOKIE_SAMESITE = "Lax"


def _activity_tracking_enabled_from_env() -> bool:
    explicit = str(os.getenv("PADESCE_ENABLE_ACTIVITY_TRACKING", "") or "").strip().lower()
    if explicit in {"1", "true", "yes", "on"}:
        return True
    if explicit in {"0", "false", "no", "off"}:
        return False
    return DATABASES.get("default", {}).get("ENGINE") != "django.db.backends.sqlite3"


PADESCE_ENABLE_ACTIVITY_TRACKING = _activity_tracking_enabled_from_env()

if PADESCE_OPERATOR_AUTH_ENABLED:
    AUTHENTICATION_BACKENDS = [
        "App_PADESCE.core.operator_auth_backends.OperatorAuthenticationBackend",
    ]
elif DATABASES.get("default", {}).get("ENGINE") == "django.db.backends.sqlite3":
    AUTHENTICATION_BACKENDS = [
        "App_PADESCE.core.auth_backends.SQLiteSafeModelBackend",
    ]

# Security headers (activated when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Logging configuration: app + access logs
LOG_DIR = Path(os.getenv("DJANGO_LOG_DIR", str(BASE_DIR / "logs")))
LOG_MAX_BYTES = _int_env("DJANGO_LOG_MAX_BYTES", 10 * 1024 * 1024, minimum=1024)
LOG_BACKUP_COUNT = _int_env("DJANGO_LOG_BACKUP_COUNT", 5, minimum=1)
try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except Exception:
    fallback_dir = Path(tempfile.gettempdir()) / "padesce_logs"
    fallback_dir.mkdir(parents=True, exist_ok=True)
    LOG_DIR = fallback_dir
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
        "access": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "app.log",
            "maxBytes": LOG_MAX_BYTES,
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": "verbose",
        },
        "access_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "access.log",
            "maxBytes": LOG_MAX_BYTES,
            "backupCount": LOG_BACKUP_COUNT,
            "encoding": "utf-8",
            "formatter": "access",
        },
    },
    "loggers": {
        "django": {"handlers": ["console", "app_file"], "level": "INFO"},
        "django.server": {
            "handlers": ["access_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "App_PADESCE": {"handlers": ["console", "app_file"], "level": "INFO"},
    },
}

# Clé secrète pour l'export Excel automatisé (script fill_excel.py)
EXPORT_API_KEY = os.getenv("EXPORT_API_KEY", "")
CGA_PUBLIC_API_KEY = os.getenv("CGA_PUBLIC_API_KEY", EXPORT_API_KEY)

# SMS provider (Obit SMS)
OBIT_API_KEY = os.getenv("OBIT_API_KEY", "")
OBIT_SENDER = os.getenv("OBIT_SENDER", "NAUMUR")
OBIT_API_URL = os.getenv("OBIT_API_URL", "https://obitsms.com/api/v2/bulksms")
OBIT_COUNTRY = os.getenv("OBIT_COUNTRY", "237")

# ---------------------------------------------------------------------------
# Email / SMTP — rapport journalier
# ---------------------------------------------------------------------------
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.smtp.EmailBackend"
        if not DEBUG
        else "django.core.mail.backends.console.EmailBackend"
    ),
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in ("1", "true", "yes")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
REPORT_EMAIL_TO = os.getenv("REPORT_EMAIL_TO", "")
DEPLOYMENT_REPORT_EMAIL_TO = os.getenv("DEPLOYMENT_REPORT_EMAIL_TO", "jackbrayan1707@gmail.com")
DEPLOYMENT_EMAIL_BACKEND = os.getenv(
    "DEPLOYMENT_EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
