"""
Django settings for App_PADESCE project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import os
import tempfile
from pathlib import Path
from urllib.parse import unquote, urlparse


def load_env_file(env_path: Path) -> None:
    """
    Charge un fichier .env simple (clé=valeur, sans quotes) si présent.
    Ne remplace pas une variable déjà définie dans l'environnement.
    """
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if (
            not line
            or line.startswith("#")
            or line.startswith("<<<<<<<")
            or line.startswith("=======")
            or line.startswith(">>>>>>>")
            or "=" not in line
        ):
            continue
        key, value = line.split("=", 1)
        key = key.strip().lstrip("\ufeff")
        value = value.strip()
        if not key or any(char.isspace() for char in key):
            continue
        os.environ.setdefault(key, value)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement locales si presentes.
load_env_file(BASE_DIR / ".env")
load_env_file(BASE_DIR / ".env.local")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")
PUBLIC_CONSULTANT_ACCESS = os.getenv("PUBLIC_CONSULTANT_ACCESS", "False").lower() in (
    "1",
    "true",
    "yes",
)
PUBLIC_ANALYSIS_AUTO_LOGIN = os.getenv("PUBLIC_ANALYSIS_AUTO_LOGIN", "True").lower() in (
    "1",
    "true",
    "yes",
)
PUBLIC_ANALYSIS_AUTO_LOGIN_USERNAME = os.getenv(
    "PUBLIC_ANALYSIS_AUTO_LOGIN_USERNAME",
    "yanava",
).strip()
PUBLIC_ANALYSIS_AUTO_LOGIN_PASSWORD = os.getenv(
    "PUBLIC_ANALYSIS_AUTO_LOGIN_PASSWORD",
    "PADESCE1234",
)
PUBLIC_ANALYSIS_AUTO_LOGIN_PREFIXES = (
    "/satisfaction-apprenants/analyse/",
    "/satisfaction-formateurs/analyse/",
    "/analyses/fast-stats/",
    "/classe/",
    "/prestation/",
    "/analyse/appels/apprenant/",
    "/analyse/appels/formateur/",
)

ALLOWED_HOSTS_ENV = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(",") if host.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*", "app-padesce.onrender.com", "call.naumur.com", "192.168.1.162"]
CSRF_TRUSTED_ORIGINS_ENV = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(",") if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Applications métiers
    "App_PADESCE.core",
    "App_PADESCE.formations",
    "App_PADESCE.apprenants",
    "App_PADESCE.presences",
    "App_PADESCE.satisfaction_apprenants",
    "App_PADESCE.satisfaction_formateurs",
    "App_PADESCE.environnement",
    "App_PADESCE.messaging",
    "App_PADESCE.reporting",
    "App_PADESCE.beneficiaires",
    "App_PADESCE.appels",
]

HAS_CHANNELS = importlib.util.find_spec("channels") is not None
if HAS_CHANNELS:
    INSTALLED_APPS.insert(6, "channels")

MIDDLEWARE = [
    "App_PADESCE.core.middleware.PathPrefixMiddleware",
    "App_PADESCE.core.middleware.FriendlyErrorPagesMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "App_PADESCE.core.middleware.LoginRequiredMiddleware",
    "App_PADESCE.core.middleware.UserActivityMiddleware",
    "App_PADESCE.core.middleware.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "App_PADESCE.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "App_PADESCE.core.context_processors.navbar",
            ],
        },
    },
]

WSGI_APPLICATION = "App_PADESCE.wsgi.application"
if HAS_CHANNELS:
    ASGI_APPLICATION = "App_PADESCE.asgi.application"
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def _postgres_sslmode_for_host(host: str) -> str:
    sslmode = str(os.getenv("POSTGRES_SSLMODE", "") or "").strip().lower()
    normalized_host = str(host or "").strip().lower()
    if sslmode == "require" and normalized_host in {"localhost", "127.0.0.1", "::1"}:
        return "prefer"
    return sslmode


def _database_settings_from_env() -> dict:
    database_url = str(os.getenv("DATABASE_URL", "") or "").strip()
    if database_url:
        parsed = urlparse(database_url)
        if parsed.scheme in {"postgres", "postgresql"}:
            host = parsed.hostname or os.getenv("POSTGRES_HOST", "") or "localhost"
            config = {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": unquote(parsed.path.lstrip("/"))
                or str(os.getenv("POSTGRES_DB", "") or "postgres"),
                "USER": unquote(parsed.username or os.getenv("POSTGRES_USER", "") or ""),
                "PASSWORD": unquote(parsed.password or os.getenv("POSTGRES_PASSWORD", "") or ""),
                "HOST": host,
                "PORT": str(parsed.port or os.getenv("POSTGRES_PORT", "") or "5432"),
            }
            sslmode = _postgres_sslmode_for_host(host)
            if sslmode:
                config["OPTIONS"] = {"sslmode": sslmode}
            return config

    engine = str(os.getenv("DB_ENGINE", "") or "").strip().lower()
    if engine in {"postgres", "postgresql", "pgsql"}:
        host = str(os.getenv("POSTGRES_HOST", "") or "localhost")
        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": str(os.getenv("POSTGRES_DB", "") or "postgres"),
            "USER": str(os.getenv("POSTGRES_USER", "") or ""),
            "PASSWORD": str(os.getenv("POSTGRES_PASSWORD", "") or ""),
            "HOST": host,
            "PORT": str(os.getenv("POSTGRES_PORT", "") or "5432"),
        }
        sslmode = _postgres_sslmode_for_host(host)
        if sslmode:
            config["OPTIONS"] = {"sslmode": sslmode}
        return config

    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": int(str(os.getenv("SQLITE_TIMEOUT_SECONDS", "20") or "20")),
        },
    }


DATABASES = {"default": _database_settings_from_env()}
if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    DATABASES["default"]["CONN_MAX_AGE"] = int(
        str(os.getenv("POSTGRES_CONN_MAX_AGE", "60") or "60")
    )
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

# Token secret pour le déclenchement automatique des backups (GitHub Actions)
BACKUP_TRIGGER_TOKEN = os.getenv("BACKUP_TRIGGER_TOKEN", "")

# Microsoft Graph / Teams
MICROSOFT_GRAPH_TENANT_ID = str(os.getenv("MICROSOFT_GRAPH_TENANT_ID", "") or "").strip()
MICROSOFT_GRAPH_CLIENT_ID = str(os.getenv("MICROSOFT_GRAPH_CLIENT_ID", "") or "").strip()
MICROSOFT_GRAPH_CLIENT_SECRET = str(os.getenv("MICROSOFT_GRAPH_CLIENT_SECRET", "") or "").strip()
MICROSOFT_GRAPH_PRIMARY_DOMAIN = str(os.getenv("MICROSOFT_GRAPH_PRIMARY_DOMAIN", "") or "").strip()
MICROSOFT_GRAPH_REDIRECT_URI = str(os.getenv("MICROSOFT_GRAPH_REDIRECT_URI", "") or "").strip()
MICROSOFT_TEAMS_DEFAULT_TEAM_ID = str(os.getenv("MICROSOFT_TEAMS_DEFAULT_TEAM_ID", "") or "").strip()
PADESCE_DESCENTE_WORKBOOK_PATH = str(os.getenv("PADESCE_DESCENTE_WORKBOOK_PATH", "") or "").strip()
MICROSOFT_GRAPH_AUTHORITY = (
    f"https://login.microsoftonline.com/{MICROSOFT_GRAPH_TENANT_ID}"
    if MICROSOFT_GRAPH_TENANT_ID
    else ""
)
MICROSOFT_GRAPH_CHANNEL_SCOPES = [
    "openid",
    "profile",
    "offline_access",
    "User.Read",
    "ChannelMessage.Send",
    "Team.ReadBasic.All",
    "Channel.ReadBasic.All",
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_DIR = BASE_DIR / "static"
STATICFILES_DIRS = [STATIC_DIR] if STATIC_DIR.exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"
CSRF_FAILURE_VIEW = "App_PADESCE.core.error_views.csrf_failure"

def _cache_settings_from_env() -> dict:
    backend_key = str(os.getenv("PADESCE_CACHE_BACKEND", "locmem") or "").strip().lower()
    timeout = int(str(os.getenv("PADESCE_CACHE_TIMEOUT", "28800") or "28800"))
    max_entries = int(str(os.getenv("PADESCE_CACHE_MAX_ENTRIES", "5000") or "5000"))

    if backend_key in {"file", "filebased", "file_based"}:
        requested_location = str(os.getenv("PADESCE_CACHE_LOCATION", "") or "").strip()
        location_candidates = [
            Path(requested_location) if requested_location else None,
            BASE_DIR / "data" / "django_cache",
            Path(tempfile.gettempdir()) / "padesce-cache",
            BASE_DIR / ".django_cache",
        ]
        location_path = None
        seen_locations: set[str] = set()
        for candidate in location_candidates:
            if candidate is None:
                continue
            candidate_key = str(candidate)
            if candidate_key in seen_locations:
                continue
            seen_locations.add(candidate_key)
            try:
                candidate.mkdir(parents=True, exist_ok=True)
            except OSError:
                continue
            location_path = candidate
            break
        if location_path is None:
            raise RuntimeError("Impossible d'initialiser un dossier de cache Django ecrivable.")
        return {
            "default": {
                "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
                "LOCATION": str(location_path),
                "TIMEOUT": timeout,
                "OPTIONS": {
                    "MAX_ENTRIES": max_entries,
                },
            }
        }

    if backend_key in {"dummy", "none"}:
        return {
            "default": {
                "BACKEND": "django.core.cache.backends.dummy.DummyCache",
            }
        }

    return {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "padesce-session-cache",
            "TIMEOUT": timeout,
            "OPTIONS": {
                "MAX_ENTRIES": max_entries,
            },
        }
    }


CACHES = _cache_settings_from_env()

# ---------------------------------------------------------------------------
# Sessions — cached_db : lecture ultra-rapide depuis le cache,
# écriture persistante dans la base de données. Si le cache expire ou
# est vidé, la session est rechargée depuis la DB automatiquement.
# ---------------------------------------------------------------------------
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 28800  # 8 heures (en secondes)
SESSION_SAVE_EVERY_REQUEST = False  # ne sauvegarder que si modifiée
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # session survit à la fermeture du navigateur
SESSION_COOKIE_HTTPONLY = True  # non accessible via JavaScript

# Security headers (activated when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Logging configuration: app + access logs
LOG_DIR = Path(os.getenv("DJANGO_LOG_DIR", str(BASE_DIR / "logs")))
try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except Exception:
    fallback_dir = Path(tempfile.gettempdir()) / "padesce_logs"
    fallback_dir.mkdir(parents=True, exist_ok=True)
    LOG_DIR = fallback_dir
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
        "access": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "app_file": {
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "app.log",
            "formatter": "verbose",
        },
        "access_file": {
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "access.log",
            "formatter": "access",
        },
    },
    "loggers": {
        "django": {"handlers": ["console", "app_file"], "level": "INFO"},
        "django.server": {
            "handlers": ["access_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "App_PADESCE": {"handlers": ["console", "app_file"], "level": "INFO"},
    },
}

# SMS provider (Obit SMS)
OBIT_API_KEY = os.getenv("OBIT_API_KEY", "")
OBIT_SENDER = os.getenv("OBIT_SENDER", "NAUMUR")
OBIT_API_URL = os.getenv("OBIT_API_URL", "https://obitsms.com/api/v2/bulksms")
OBIT_COUNTRY = os.getenv("OBIT_COUNTRY", "237")

# ---------------------------------------------------------------------------
# Email / SMTP — rapport journalier
# ---------------------------------------------------------------------------
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.smtp.EmailBackend"
        if not DEBUG
        else "django.core.mail.backends.console.EmailBackend"
    ),
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
REPORT_EMAIL_TO = os.getenv("REPORT_EMAIL_TO", "")
DEPLOYMENT_REPORT_EMAIL_TO = os.getenv("DEPLOYMENT_REPORT_EMAIL_TO", "jackbrayan1707@gmail.com")
DEPLOYMENT_EMAIL_BACKEND = os.getenv(
    "DEPLOYMENT_EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
