"""
Django settings for App_PADESCE project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import os
from pathlib import Path
from urllib.parse import unquote, urlparse


def load_env_file(env_path: Path) -> None:
    """
    Charge un fichier .env simple (clé=valeur, sans quotes) si présent.
    Ne remplace pas une variable déjà définie dans l'environnement.
    """
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if (
            not line
            or line.startswith("#")
            or line.startswith("<<<<<<<")
            or line.startswith("=======")
            or line.startswith(">>>>>>>")
            or "=" not in line
        ):
            continue
        key, value = line.split("=", 1)
        key = key.strip().lstrip("\ufeff")
        value = value.strip()
        if not key or any(char.isspace() for char in key):
            continue
        os.environ.setdefault(key, value)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement locales si presentes.
load_env_file(BASE_DIR / ".env")
load_env_file(BASE_DIR / ".env.local")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")
PUBLIC_CONSULTANT_ACCESS = os.getenv("PUBLIC_CONSULTANT_ACCESS", "False").lower() in ("1", "true", "yes")

ALLOWED_HOSTS_ENV = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(",") if host.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*", "app-padesce.onrender.com", "call.naumur.com","192.168.1.162"]
CSRF_TRUSTED_ORIGINS_ENV = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(",") if origin.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Applications métiers
    'App_PADESCE.core',
    'App_PADESCE.formations',
    'App_PADESCE.apprenants',
    'App_PADESCE.presences',
    'App_PADESCE.satisfaction_apprenants',
    'App_PADESCE.satisfaction_formateurs',
    'App_PADESCE.environnement',
    'App_PADESCE.messaging',
    'App_PADESCE.reporting',
    'App_PADESCE.beneficiaires',
    'App_PADESCE.appels',
]

HAS_CHANNELS = importlib.util.find_spec("channels") is not None
if HAS_CHANNELS:
    INSTALLED_APPS.insert(6, 'channels')

MIDDLEWARE = [
    'App_PADESCE.core.middleware.FriendlyErrorPagesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'App_PADESCE.core.middleware.LoginRequiredMiddleware',
    'App_PADESCE.core.middleware.UserActivityMiddleware',
    'App_PADESCE.core.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'App_PADESCE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'App_PADESCE.wsgi.application'
if HAS_CHANNELS:
    ASGI_APPLICATION = 'App_PADESCE.asgi.application'
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _database_settings_from_env() -> dict:
    database_url = str(os.getenv("DATABASE_URL", "") or "").strip()
    if database_url:
        parsed = urlparse(database_url)
        if parsed.scheme in {"postgres", "postgresql"}:
            return {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": unquote(parsed.path.lstrip("/")) or str(os.getenv("POSTGRES_DB", "") or "postgres"),
                "USER": unquote(parsed.username or os.getenv("POSTGRES_USER", "") or ""),
                "PASSWORD": unquote(parsed.password or os.getenv("POSTGRES_PASSWORD", "") or ""),
                "HOST": parsed.hostname or os.getenv("POSTGRES_HOST", "") or "localhost",
                "PORT": str(parsed.port or os.getenv("POSTGRES_PORT", "") or "5432"),
            }

    engine = str(os.getenv("DB_ENGINE", "") or "").strip().lower()
    if engine in {"postgres", "postgresql", "pgsql"}:
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": str(os.getenv("POSTGRES_DB", "") or "postgres"),
            "USER": str(os.getenv("POSTGRES_USER", "") or ""),
            "PASSWORD": str(os.getenv("POSTGRES_PASSWORD", "") or ""),
            "HOST": str(os.getenv("POSTGRES_HOST", "") or "localhost"),
            "PORT": str(os.getenv("POSTGRES_PORT", "") or "5432"),
        }

    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


DATABASES = {"default": _database_settings_from_env()}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_DIR = BASE_DIR / 'static'
STATICFILES_DIRS = [STATIC_DIR] if STATIC_DIR.exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"
if importlib.util.find_spec("App_PADESCE.core.error_views") is not None:
    CSRF_FAILURE_VIEW = "App_PADESCE.core.error_views.csrf_failure"

# ---------------------------------------------------------------------------
# Cache — In-process memory cache (fast, no external service needed).
# For multi-server deployments replace with Redis or Memcached.
# ---------------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "padesce-session-cache",
        "TIMEOUT": 28800,  # 8 heures en secondes
        "OPTIONS": {
            "MAX_ENTRIES": 5000,  # nombre max d'entrées en mémoire
        },
    }
}

# ---------------------------------------------------------------------------
# Sessions — cached_db : lecture ultra-rapide depuis le cache,
# écriture persistante dans la base de données. Si le cache expire ou
# est vidé, la session est rechargée depuis la DB automatiquement.
# ---------------------------------------------------------------------------
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 28800          # 8 heures (en secondes)
SESSION_SAVE_EVERY_REQUEST = False  # ne sauvegarder que si modifiée
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # session survit à la fermeture du navigateur
SESSION_COOKIE_HTTPONLY = True      # non accessible via JavaScript

# Security headers (activated when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Logging configuration: app + access logs
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
        "access": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "app_file": {
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "app.log",
            "formatter": "verbose",
        },
        "access_file": {
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "access.log",
            "formatter": "access",
        },
    },
    "loggers": {
        "django": {"handlers": ["console", "app_file"], "level": "INFO"},
        "django.server": {"handlers": ["access_file", "console"], "level": "INFO", "propagate": False},
        "App_PADESCE": {"handlers": ["console", "app_file"], "level": "INFO"},
    },
}

# SMS provider (Obit SMS)
OBIT_API_KEY = os.getenv("OBIT_API_KEY", "")
OBIT_SENDER = os.getenv("OBIT_SENDER", "NAUMUR")
OBIT_API_URL = os.getenv("OBIT_API_URL", "https://obitsms.com/api/v2/bulksms")
OBIT_COUNTRY = os.getenv("OBIT_COUNTRY", "237")

# ---------------------------------------------------------------------------
# Email / SMTP — rapport journalier
# ---------------------------------------------------------------------------
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend" if not DEBUG else "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
REPORT_EMAIL_TO = os.getenv("REPORT_EMAIL_TO", "")
DEPLOYMENT_REPORT_EMAIL_TO = os.getenv("DEPLOYMENT_REPORT_EMAIL_TO", "jackbrayan1707@gmail.com")
DEPLOYMENT_EMAIL_BACKEND = os.getenv("DEPLOYMENT_EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
