# Generated by Django 6.0.2 on 2026-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_rename_reporting_c_code_96f31f_idx_reporting_c_code_c4eaac_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidationrecord',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='consolidationrecord',
            name='latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='consolidationrecord',
            name='longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='consolidationrecord',
            name='tel_formateur',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
