# Generated by Django 6.0 on 2026-01-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0002_alter_appel_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appel',
            name='deja_forme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appel',
            name='formation_padesce',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appel',
            name='type_formation_declaree',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
