# Generated by Django 5.2.2 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction_apprenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionapprenant',
            name='audio_appel',
            field=models.FileField(blank=True, null=True, upload_to='enquetes/satisfaction_apprenants/'),
        ),
    ]
