# Generated by Django 5.2.2 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("satisfaction_apprenants", "0002_satisfactionapprenant_audio_appel"),
    ]

    operations = [
        migrations.AddField(
            model_name="satisfactionapprenant",
            name="transcription",
            field=models.TextField(blank=True),
        ),
    ]
