# Generated by Django 5.0.6 on 2026-01-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_prestation_durees_jalons'),
        ('satisfaction_apprenants', '0003_satisfactionapprenant_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionapprenant',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions_apprenants', to='formations.classe'),
        ),
    ]
