# Generated by Django 6.0 on 2026-03-09 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0009_appelanswers_appeltranscription'),
        ('apprenants', '0006_import_columns'),
        ('satisfaction_apprenants', '0004_alter_satisfactionapprenant_classe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_path', models.CharField(blank=True, max_length=500)),
                ('transcript', models.TextField(blank=True)),
                ('engine', models.CharField(blank=True, max_length=120)),
                ('extracted_answers_json', models.JSONField(blank=True, default=dict)),
                ('appel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to='appels.appel')),
                ('apprenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to='apprenants.apprenant')),
                ('enqueteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transcriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='transcripti_created_e8d9e3_idx'), models.Index(fields=['apprenant'], name='transcripti_apprena_3d020c_idx')],
            },
        ),
    ]
