# Generated by Django 6.0 on 2026-03-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction_apprenants', '0005_transcription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satisfactionapprenant',
            old_name='q3_rythme_formation',
            new_name='q3_maitrise_contenu',
        ),
        migrations.RenameField(
            model_name='satisfactionapprenant',
            old_name='q4_qualite_supports',
            new_name='q4_salle_adequate',
        ),
        migrations.RenameField(
            model_name='satisfactionapprenant',
            old_name='q5_applicabilite_contenu',
            new_name='q5_materiel_disponible',
        ),
        migrations.RenameField(
            model_name='satisfactionapprenant',
            old_name='q6_organisation_logistique',
            new_name='q6_organisation_temps',
        ),
        migrations.RenameField(
            model_name='satisfactionapprenant',
            old_name='q7_respect_programme',
            new_name='q7_utilite_formation',
        ),
    ]
