# Generated by Django 6.0.2 on 2026-04-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction_apprenants', '0007_satisfactionapprenant_appel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionapprenant',
            name='audio_appel',
            field=models.FileField(blank=True, null=True, upload_to='enquetes/satisfaction_apprenants/'),
        ),
    ]
