# Generated by Django 6.0.2 on 2026-04-10 22:44

import App_PADESCE.satisfaction_apprenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction_apprenants', '0007_satisfactionapprenant_appel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionapprenant',
            name='audio_appel',
            field=models.FileField(blank=True, null=True, upload_to=App_PADESCE.satisfaction_apprenants.models.satisfaction_apprenant_audio_upload),
        ),
    ]
