from django.urls import path

from App_PADESCE.core.lazy_urls import lazy_view

urlpatterns = [
    path(
        "",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_apprenants"),
        name="satisfaction_apprenants_index",
    ),
    path(
        "export/csv/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_apprenants_export_csv"),
        name="satisfaction_apprenants_export_csv",
    ),
    path(
        "export/commentaires-xlsx/",
        lazy_view(
            "App_PADESCE.satisfaction_apprenants.views.satisfaction_apprenants_export_comments_xlsx"
        ),
        name="satisfaction_apprenants_export_comments_xlsx",
    ),
    path(
        "analyse/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_dashboard"),
        name="satisfaction_dashboard",
    ),
    path(
        "analyse/rag/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_dashboard_rag"),
        name="satisfaction_dashboard_rag",
    ),
    path(
        "analyse/general/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_general_page"),
        name="satisfaction_general_page",
    ),
    path(
        "analyse/general/toggle-exclusion/",
        lazy_view(
            "App_PADESCE.satisfaction_apprenants.views.satisfaction_general_toggle_exclusion"
        ),
        name="satisfaction_general_toggle_exclusion",
    ),
    path(
        "analyse/update-form/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_update_form_page"),
        name="satisfaction_update_form_page",
    ),
    path(
        "analyse/export/rapport-quotidien/xlsx/",
        lazy_view(
            "App_PADESCE.satisfaction_apprenants.views.satisfaction_dashboard_daily_report_xlsx"
        ),
        name="satisfaction_dashboard_daily_report_xlsx",
    ),
    path(
        "analyse/export/xlsx/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_dashboard_export_xlsx"),
        name="satisfaction_dashboard_export_xlsx",
    ),
    path(
        "analyse/export/csv/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_dashboard_export_csv"),
        name="satisfaction_dashboard_export_csv",
    ),
    path(
        "analyse/export/classes-zip/",
        lazy_view(
            (
                "App_PADESCE.satisfaction_apprenants.views."
                "satisfaction_dashboard_export_class_lists_zip"
            ),
        ),
        name="satisfaction_dashboard_export_class_lists_zip",
    ),
    path(
        "analyse/export/prestations-xlsx/",
        lazy_view(
            (
                "App_PADESCE.satisfaction_apprenants.views."
                "satisfaction_dashboard_export_prestation_lists_xlsx"
            ),
        ),
        name="satisfaction_dashboard_export_prestation_lists_xlsx",
    ),
    path(
        "analyse/export/chapeau/",
        lazy_view(
            "App_PADESCE.satisfaction_apprenants.views.satisfaction_dashboard_export_chapeau"
        ),
        name="satisfaction_dashboard_export_chapeau",
    ),
    path(
        "analyse/map-data/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_map_data"),
        name="satisfaction_map_data",
    ),
    path(
        "analyse/apprenants-manquants/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.apprenants_manquants_page"),
        name="apprenants_manquants_page",
    ),
    path(
        "analyse/import-manquants/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.import_missing_apprenants"),
        name="import_missing_apprenants",
    ),
    path(
        "analyse/import-notifications/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.import_notifications_poll"),
        name="import_notifications_poll",
    ),
    path(
        "analyse/sync-telephones/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.sync_phones_from_consolidation"),
        name="sync_phones_from_consolidation",
    ),
    path(
        "analyse/sync-reference/",
        lazy_view("App_PADESCE.satisfaction_apprenants.views.satisfaction_sync_reference_page"),
        name="satisfaction_sync_reference_page",
    ),
    path(
        "export/moyennes-generales/xlsx/",
        lazy_view(
            "App_PADESCE.satisfaction_apprenants.views."
            "export_apprenant_global_averages_xlsx"
        ),
        name="export_apprenant_global_averages",
    ),
]
