# Generated by Django 5.1.3 on 2026-04-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_useractivityevent_and_live_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useractivityevent",
            new_name="core_userac_user_id_0cac8f_idx",
            old_name="core_userac_user_id_aa8d99_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivityevent",
            new_name="core_userac_event_t_3ad30d_idx",
            old_name="core_userac_event_t_5a6ed8_idx",
        ),
    ]
