# Generated by Django 6.0.2 on 2026-04-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_userac_user_id_aa8d99_idx_core_userac_user_id_0cac8f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOptimizationSnapshot',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('appels_fingerprint', models.CharField(blank=True, default='', max_length=320)),
                ('source_fingerprint', models.CharField(blank=True, default='', max_length=640)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snapshot optimisation appels PADESCE',
            },
        ),
        migrations.CreateModel(
            name='MaterializedDashboardPayload',
            fields=[
                ('cache_key_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('valid_until', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Payload dashboard matérialisé',
            },
        ),
    ]
