# Generated by Django 6.0 on 2026-03-04 10:22

import App_PADESCE.appels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0007_appelcga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='audio_file',
            field=models.FileField(
                blank=True, max_length=255, null=True, 
                upload_to=App_PADESCE.appels.models.appel_audio_upload
            ),
        ),
        migrations.AlterField(
            model_name='appelcga',
            name='audio_file',
            field=models.FileField(
                blank=True, max_length=255, null=True, 
                upload_to=App_PADESCE.appels.models.appel_cga_audio_upload
            ),
        ),
    ]
