# Generated by Django 6.0.2 on 2026-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0015_appelformateur_commentaires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appelanswers',
            name='q3_maitrise_contenu',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appelanswers',
            name='q4_salle_adequate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appelanswers',
            name='q5_materiel_disponible',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appelanswers',
            name='q6_organisation_temps',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appelanswers',
            name='q7_utilite_formation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
