# Generated by Django 6.0.2 on 2026-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0016_alter_appelanswers_q3_maitrise_contenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='type_formation_declaree',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appelformateur',
            name='date_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appelformateur',
            name='formation',
            field=models.TextField(blank=True),
        ),
    ]
