# Generated by Django 6.0.2 on 2026-04-10 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0020_add_new_call_status_choices'),
        ('formations', '0005_widen_lieu_code_for_postgres_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appel',
            index=models.Index(fields=['is_active', 'status'], name='appels_appe_is_acti_323e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='appel',
            index=models.Index(fields=['is_active', 'classe_label'], name='appels_appe_is_acti_604209_idx'),
        ),
        migrations.AddIndex(
            model_name='appel',
            index=models.Index(fields=['is_active', 'prestataire'], name='appels_appe_is_acti_bebdbf_idx'),
        ),
        migrations.AddIndex(
            model_name='appel',
            index=models.Index(fields=['is_active', 'beneficiaire'], name='appels_appe_is_acti_3788f5_idx'),
        ),
    ]
