# Generated by Django 5.2.12 on 2026-04-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0021_appel_appels_appe_is_acti_323e1c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appel',
            name='appels_appe_is_acti_323e1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='appel',
            name='appels_appe_is_acti_604209_idx',
        ),
        migrations.RemoveIndex(
            model_name='appel',
            name='appels_appe_is_acti_bebdbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='appel',
            name='appels_appe_is_acti_3788f5_idx',
        ),
    ]
