# Generated by Django 6.0.2 on 2026-04-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0022_remove_appel_appels_appe_is_acti_323e1c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='appel',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('appel_tente', 'Appel Tenté'), ('appel_reussi', 'Appel Réussi'), ('formulaire_rempli', 'Formulaire Rempli'), ('formulaire_avec_audio', 'Formulaire avec Audio'), ('en_cours', 'En cours'), ('pause', 'Pause'), ('a_rappeler', 'A rappeler'), ('termine', 'Termine')], db_index=True, default='en_attente', max_length=25),
        ),
    ]
