# Generated by Django 6.0 on 2026-04-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appels", "0023_add_appel_index_is_active_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appelcga",
            name="indisponible",
            field=models.CharField(blank=True, max_length=10, verbose_name="Indisponible"),
        ),
        migrations.AddField(
            model_name="appelcga",
            name="interet",
            field=models.CharField(blank=True, max_length=10, verbose_name="Intérêt"),
        ),
        migrations.AddField(
            model_name="appelcga",
            name="mauvais_numero",
            field=models.CharField(blank=True, max_length=10, verbose_name="Mauvais numéro"),
        ),
    ]
