# Generated by Django 6.0 on 2026-04-20 12:07

from django.db import migrations


def delete_pending_cga(apps, schema_editor):
    AppelCGA = apps.get_model("appels", "AppelCGA")
    # Suppression de tous les appels en attente
    AppelCGA.objects.filter(status="en_attente").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("appels", "0024_appelcga_indisponible_appelcga_interet_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_pending_cga),
    ]
