# Generated by Django 6.0 on 2026-04-20 12:29

from django.db import migrations


def delete_pending_cga(apps, schema_editor):
    AppelCGA = apps.get_model("appels", "AppelCGA")
    # Seconde suppression des appels en attente suite a import accidentel
    AppelCGA.objects.filter(status="en_attente").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("appels", "0025_delete_pending_cga_data"),
    ]

    operations = [
        migrations.RunPython(delete_pending_cga),
    ]
