# Generated by Django 6.0.2 on 2026-05-19 12:50

import App_PADESCE.appels.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0028_callalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelPasForme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(max_length=120, unique=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('est_forme', models.CharField(blank=True, max_length=80)),
                ('prestation_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('prestataire', models.CharField(blank=True, max_length=255)),
                ('beneficiaire', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('appel_tente', 'Appel Tenté'), ('appel_reussi', 'Appel Réussi'), ('formulaire_rempli', 'Formulaire Rempli'), ('formulaire_avec_audio', 'Formulaire avec Audio'), ('en_cours', 'En cours'), ('pause', 'Pause'), ('a_rappeler', 'A rappeler'), ('termine', 'Termine')], db_index=True, default='en_attente', max_length=25)),
                ('rappel_at', models.DateTimeField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, max_length=255, null=True, upload_to=App_PADESCE.appels.models.appel_pas_forme_audio_upload)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('connait_structure', models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3)),
                ('membre_structure', models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3)),
                ('a_assiste_formation', models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3)),
                ('connait_theme', models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=3)),
                ('nombre_seances', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('satisfaction_completed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_pas_forme_lock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='appels_appe_nom_72e1ab_idx'), models.Index(fields=['telephone'], name='appels_appe_telepho_98a749_idx'), models.Index(fields=['prestation_id'], name='appels_appe_prestat_b6b26c_idx'), models.Index(fields=['prestataire'], name='appels_appe_prestat_fe3f86_idx'), models.Index(fields=['beneficiaire'], name='appels_appe_benefic_02fcd2_idx')],
            },
        ),
    ]
