# Generated by Django 5.2.2 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("satisfaction_formateurs", "0002_satisfactionformateur_audio_appel"),
    ]

    operations = [
        migrations.AddField(
            model_name="satisfactionformateur",
            name="transcription",
            field=models.TextField(blank=True),
        ),
    ]
