# Generated by Django 6.0.2 on 2026-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_seed_beneficiaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
