# Generated by Django 6.0.2 on 2026-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_widen_fields_for_postgres_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
