# Generated by Django 6.0 on 2026-05-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0010_fix_phase_assignments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phase",
            options={"ordering": ["vague", "id_phase"]},
        ),
        migrations.AddField(
            model_name="phase",
            name="nom",
            field=models.CharField(default="vague", max_length=100, verbose_name="Nom de la phase"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phase",
            name="vague",
            field=models.PositiveIntegerField(default=1, verbose_name="Numéro de vague"),
            preserve_default=False,
        ),
    ]
