# Generated by Django

from django.db import migrations


def update_phase_data(apps, schema_editor):
    """
    Met à jour les données existantes de la table Phase
    """
    Phase = apps.get_model('formations', 'Phase')
    
    # Mettre à jour la phase 1 (id_phase = 1)
    Phase.objects.filter(id_phase=1).update(
        nom='Vague 1',
        vague=1
    )
    
    # Mettre à jour la phase 2 (id_phase = 2) 
    Phase.objects.filter(id_phase=2).update(
        nom='Vague 1 (POST)',
        vague=1
    )


class Migration(migrations.Migration):
    dependencies = [
        ('formations', '0011_alter_phase_options_phase_nom_phase_vague'),
    ]

    operations = [
        migrations.RunPython(update_phase_data, reverse_code=migrations.RunPython.noop),
    ]
