# Generated by Django 6.0.2 on 2026-04-10 22:44

import App_PADESCE.satisfaction_formateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction_formateurs', '0004_satisfactionformateur_update_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionformateur',
            name='audio_appel',
            field=models.FileField(blank=True, null=True, upload_to=App_PADESCE.satisfaction_formateurs.models.satisfaction_formateur_audio_upload),
        ),
    ]
