# Generated by Django 5.2.2 on 2025-12-14 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('presence', models.CharField(choices=[('PR', 'Présent'), ('AB', 'Absent')], default='PR', max_length=2)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent')], default='present', max_length=10)),
                ('moyen_enregistrement', models.CharField(choices=[('C', 'Code'), ('P', 'Papier')], default='C', max_length=1)),
                ('remarques', models.TextField(blank=True)),
                ('heure_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='apprenants.apprenant')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='formations.classe')),
                ('enqueteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_saisies', to=settings.AUTH_USER_MODEL)),
                ('inspecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='formations.inspecteur')),
            ],
            options={
                'ordering': ['-date', 'classe'],
                'indexes': [models.Index(fields=['classe', 'date'], name='presences_p_classe__1ae51b_idx')],
                'constraints': [models.UniqueConstraint(fields=('classe', 'apprenant', 'date'), name='presence_unique_par_jour')],
            },
        ),
    ]
