# Generated by Django 5.2.2 on 2025-12-14 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_heure', models.DateTimeField()),
                ('texte', models.TextField()),
                ('cible_description', models.CharField(blank=True, max_length=255)),
                ('message_envoye_json', models.JSONField(blank=True, default=list)),
                ('message_rejete_json', models.JSONField(blank=True, default=list)),
                ('motif_rejet', models.TextField(blank=True)),
                ('enqueteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=30)),
                ('genre', models.CharField(blank=True, max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('fonction', models.CharField(blank=True, max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('nb_annees_experience', models.PositiveIntegerField(default=0)),
                ('ville_residence', models.CharField(blank=True, max_length=120)),
                ('type_formation', models.CharField(blank=True, max_length=255)),
                ('intitule_formation', models.CharField(blank=True, max_length=255)),
                ('fenetre', models.CharField(blank=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('apprenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='apprenants.apprenant')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.formation')),
                ('prestataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.prestataire')),
            ],
            options={
                'ordering': ['nom_complet'],
                'indexes': [models.Index(fields=['prestataire', 'fenetre'], name='messaging_c_prestat_a8b1e2_idx')],
            },
        ),
    ]
