# Generated by Django 5.2.2 on 2025-12-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_structure', models.CharField(max_length=255)),
                ('type_structure', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('departement', models.CharField(blank=True, max_length=120)),
                ('arrondissement', models.CharField(blank=True, max_length=120)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['nom_structure'],
            },
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('specialite', models.CharField(blank=True, max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('nb_annees_experience', models.PositiveIntegerField(default=0)),
                ('fenetre', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('ville_residence', models.CharField(blank=True, max_length=120)),
                ('autres_infos', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('nom_harmonise', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('non_demarre', 'Non démarré'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='non_demarre', max_length=20)),
                ('fenetre', models.CharField(blank=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Inspecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom_lieu', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('departement', models.CharField(blank=True, max_length=120)),
                ('arrondissement', models.CharField(blank=True, max_length=120)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('longitude', models.CharField(blank=True, max_length=60)),
                ('latitude', models.CharField(blank=True, max_length=60)),
                ('precision', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom_lieu'],
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('type_structure', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('effectif_a_former', models.PositiveIntegerField(default=0)),
                ('femmes', models.PositiveIntegerField(default=0)),
                ('cout_unitaire_psoaf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_formation_psoaf_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cout_unitaire_mcdc_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_mcdc_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations', to='formations.beneficiaire')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='formations.formation')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='formations.prestataire')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('intitule_formation', models.CharField(max_length=255)),
                ('fenetre', models.CharField(blank=True, max_length=50)),
                ('cohorte', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('non_demarre', 'Non démarré'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='non_demarre', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='formations.formateur')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='formations.formation')),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='formations.lieu')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='formations.prestation')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['prestation', 'fenetre'], name='formations__prestat_c1f8bd_idx')],
            },
        ),
    ]
