# Generated by Django 5.0.6 on 2025-12-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_default_groups'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_model_n_36490f_idx',
            old_name='core_audit_model_n_83dc92_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_timesta_80074f_idx',
            old_name='core_audit_timesta_1e3577_idx',
        ),
    ]
